### ISSUE TITLE
posted like facebook

### ISSUE THREAD

**Issue by Lucas-Pat** [Lucas-Pat/Lucas-Pat#4]
facebook ab thanks Sherri
![Screenshot 2024-01-11 11 59 28 AM](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/c1c5e280-7739-4f7e-860d-74630ca5ccf9)
![Screenshot 2024-01-11 11 59 34 AM](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/70c337fb-9a1c-41bf-8d04-3fd2142b2342)
[Screen recording 2024-01-29 8.29.00 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/336dc5d2-2320-4cef-89d4-b6663f4fb895)
[Screen recording 2024-01-29 8.30.17 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/edc15fd6-e7cc-4726-9bcd-aa56a571ba82)

**Comment by Lucas-Pat** [comment]
another one ab
[Screen recording 2024-01-29 8.32.19 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/e392894a-bea9-4df2-a6c2-904ae78b622f)
![Screenshot 2024-01-29 8 33 57 PM](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/a161e7be-56da-4df4-a554-92e5ac97e3af)
[Screen recording 2024-01-29 8.33.55 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/e3f53e86-e189-416d-bb96-db2fd786d604)

**Comment by Lucas-Pat** [comment]
hi ab attached to gmail
[Screen recording 2024-01-29 8.46.27 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/c3aabb06-57f2-4fc2-8f27-5f009995254b)

**Comment by Lucas-Pat** [comment]
hi ab weird screenshot
![Screenshot 2024-01-29 8 49 25 PM](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/e56fba80-9dd9-41fe-8c20-6c5eadb52779)
[Screen recording 2024-01-29 8.48.29 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/21b1e1e2-81a5-4a3c-879a-06da660e162a)

**Comment by Lucas-Pat** [comment]
another one ab
[Screen recording 2024-01-29 8.51.15 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/a7387596-58b1-423f-8b95-fff610e4553d)
[Screen recording 2024-01-29 8.52.26 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/98f499b5-c5e6-4a96-af6b-067c8263375c)
[Screen recording 2024-01-29 8.53.29 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/6061f72b-7417-4a6d-83b4-6b859b03d8e8)
[Screen recording 2024-01-29 8.55.29 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/89079844-5daa-44b5-abf4-30942249ac3c)

**Comment by Lucas-Pat** [comment]
thank you @burnsboyamazing
[Screen recording 2024-01-29 8.56.59 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/75497cc2-c29c-43c9-b5c7-ca322fc7695d)
[Screen recording 2024-01-29 8.57.40 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/84558faf-32ca-4d04-993a-cbed3f5a7248)

**Comment by Lucas-Pat** [comment]
hi ab again
[Screen recording 2024-01-29 8.58.16 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/80d699f0-3da4-42cb-a032-9e225702448a)

**Comment by Lucas-Pat** [comment]
hi ab submitted to https://github.com/Lucas-Pat/Lucas-Pat/issues/6.
[Screen recording 2024-01-29 9.19.48 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/a5e763a8-7ec5-4585-b41d-354a3d891540)
[Screen recording 2024-01-29 9.21.38 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/e0c15fcc-65f2-4db8-8f13-fc56f58a7fe5)

**Comment by Lucas-Pat** [comment]
running ab
[Screen recording 2024-01-29 9.31.28 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/e4a6b91f-f44c-4ed7-ab96-28b3f5a58675)
[Screen recording 2024-01-29 9.34.06 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/0e9a60fb-309e-4b2b-bcdb-ab7e2b8314ff)

**Comment by Lucas-Pat** [comment]
facebook ab
![Screenshot 2024-01-29 9 37 30 PM](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/3f5af2a9-d977-46f1-a5d0-cd223d1fdeaf)
[Screen recording 2024-01-29 9.37.06 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/b87c25e3-50b0-42d1-b5ce-a9d55e37c948)

**Comment by Lucas-Pat** [comment]
thank you ab
[Screen recording 2024-01-29 9.39.00 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/4a7cb538-7c9c-480a-be23-ec4ad7e3c9e9)

**Comment by Lucas-Pat** [comment]
ab closed issue
[Screen recording 2024-01-29 9.43.11 PM.webm](https://github.com/Lucas-Pat/Lucas-Pat/assets/158116771/2e399c8b-5a92-4189-84a3-4280e3b6eaec)

**Comment by burnsboyamazing** [comment]
Thanks, I'll check it out.

**Comment by burnsboyamazing** [comment]
Thanks, I'll check it out.
